### ISSUE TITLE
Internal server error on HTTP request

### ISSUE THREAD

**Issue by adedommelin-zz** [jamtur01/puppet-rundeck#14]
Hey, 

Just installed puppet-rundeck and I get an HTTP 500 : 

$ curl -IXGET http://127.0.0.1:8144
HTTP/1.1 500 Internal Server Error
Content-Type: text/html
Content-Length: 166296
Connection: keep-alive
Server: thin 1.5.0 codename Knife

Output on TTY running puppet-rundeck : 
ArgumentError - syntax error on line 86, col 7: `':
    /usr/lib/ruby/1.8/yaml.rb:133:in`load'
    /usr/lib/ruby/1.8/yaml.rb:133:in `load'
    /usr/lib/ruby/1.8/yaml.rb:144:in`load_file'
    /usr/lib/ruby/1.8/yaml.rb:143:in `open'
    /usr/lib/ruby/1.8/yaml.rb:143:in`load_file'
    /usr/lib/ruby/site_ruby/1.8/puppet/indirector/yaml.rb:62:in `search'
    /usr/lib/ruby/site_ruby/1.8/puppet/indirector/yaml.rb:61:in`collect'
    /usr/lib/ruby/site_ruby/1.8/puppet/indirector/yaml.rb:61:in `search'
    /usr/lib/ruby/site_ruby/1.8/puppet/indirector/indirection.rb:256:in`search'
    /usr/lib64/ruby/gems/1.8/gems/puppet-rundeck-0.0.7/lib/puppet-rundeck.rb:55:in `GET /'
    /usr/lib64/ruby/gems/1.8/gems/sinatra-1.3.3/lib/sinatra/base.rb:1264:in`call'
    /usr/lib64/ruby/gems/1.8/gems/sinatra-1.3.3/lib/sinatra/base.rb:1264:in `compile!'
    /usr/lib64/ruby/gems/1.8/gems/sinatra-1.3.3/lib/sinatra/base.rb:835:in`[]'
    /usr/lib64/ruby/gems/1.8/gems/sinatra-1.3.3/lib/sinatra/base.rb:835:in `route!'
    /usr/lib64/ruby/gems/1.8/gems/sinatra-1.3.3/lib/sinatra/base.rb:851:in`route_eval'
    /usr/lib64/ruby/gems/1.8/gems/sinatra-1.3.3/lib/sinatra/base.rb:835:in `route!'
    /usr/lib64/ruby/gems/1.8/gems/sinatra-1.3.3/lib/sinatra/base.rb:872:in`process_route'
    /usr/lib64/ruby/gems/1.8/gems/sinatra-1.3.3/lib/sinatra/base.rb:870:in `catch'
    /usr/lib64/ruby/gems/1.8/gems/sinatra-1.3.3/lib/sinatra/base.rb:870:in`process_route'
    /usr/lib64/ruby/gems/1.8/gems/sinatra-1.3.3/lib/sinatra/base.rb:834:in `route!'
    /usr/lib64/ruby/gems/1.8/gems/sinatra-1.3.3/lib/sinatra/base.rb:833:in`each'
    /usr/lib64/ruby/gems/1.8/gems/sinatra-1.3.3/lib/sinatra/base.rb:833:in `route!'
    /usr/lib64/ruby/gems/1.8/gems/sinatra-1.3.3/lib/sinatra/base.rb:936:in`dispatch!'
    /usr/lib64/ruby/gems/1.8/gems/sinatra-1.3.3/lib/sinatra/base.rb:769:in `call!'
    /usr/lib64/ruby/gems/1.8/gems/sinatra-1.3.3/lib/sinatra/base.rb:921:in`invoke'
    /usr/lib64/ruby/gems/1.8/gems/sinatra-1.3.3/lib/sinatra/base.rb:921:in `catch'
    /usr/lib64/ruby/gems/1.8/gems/sinatra-1.3.3/lib/sinatra/base.rb:921:in`invoke'
    /usr/lib64/ruby/gems/1.8/gems/sinatra-1.3.3/lib/sinatra/base.rb:769:in `call!'
    /usr/lib64/ruby/gems/1.8/gems/sinatra-1.3.3/lib/sinatra/base.rb:755:in`call'
    /usr/lib64/ruby/gems/1.8/gems/rack-protection-1.2.0/lib/rack/protection/xss_header.rb:22:in `call'
    /usr/lib64/ruby/gems/1.8/gems/rack-protection-1.2.0/lib/rack/protection/path_traversal.rb:16:in`call'
    /usr/lib64/ruby/gems/1.8/gems/rack-protection-1.2.0/lib/rack/protection/json_csrf.rb:17:in `call'
    /usr/lib64/ruby/gems/1.8/gems/rack-protection-1.2.0/lib/rack/protection/base.rb:47:in`call'
    /usr/lib64/ruby/gems/1.8/gems/rack-protection-1.2.0/lib/rack/protection/xss_header.rb:22:in `call'
    /usr/lib64/ruby/gems/1.8/gems/rack-1.4.1/lib/rack/nulllogger.rb:9:in`call'
    /usr/lib64/ruby/gems/1.8/gems/rack-1.4.1/lib/rack/head.rb:9:in `call'
    /usr/lib64/ruby/gems/1.8/gems/sinatra-1.3.3/lib/sinatra/showexceptions.rb:21:in`call'
    /usr/lib64/ruby/gems/1.8/gems/sinatra-1.3.3/lib/sinatra/base.rb:99:in `call'
    /usr/lib64/ruby/gems/1.8/gems/sinatra-1.3.3/lib/sinatra/base.rb:1389:in`call'
    /usr/lib64/ruby/gems/1.8/gems/sinatra-1.3.3/lib/sinatra/base.rb:1471:in `synchronize'
    /usr/lib64/ruby/gems/1.8/gems/sinatra-1.3.3/lib/sinatra/base.rb:1389:in`call'
    /usr/lib64/ruby/gems/1.8/gems/thin-1.5.0/lib/thin/connection.rb:81:in `pre_process'
    /usr/lib64/ruby/gems/1.8/gems/thin-1.5.0/lib/thin/connection.rb:79:in`catch'
    /usr/lib64/ruby/gems/1.8/gems/thin-1.5.0/lib/thin/connection.rb:79:in `pre_process'
    /usr/lib64/ruby/gems/1.8/gems/eventmachine-1.0.0/lib/eventmachine.rb:1037:in`call'
    /usr/lib64/ruby/gems/1.8/gems/eventmachine-1.0.0/lib/eventmachine.rb:1037:in `spawn_threadpool'
    /usr/lib64/ruby/gems/1.8/gems/eventmachine-1.0.0/lib/eventmachine.rb:1033:in`initialize'
    /usr/lib64/ruby/gems/1.8/gems/eventmachine-1.0.0/lib/eventmachine.rb:1033:in `new'
    /usr/lib64/ruby/gems/1.8/gems/eventmachine-1.0.0/lib/eventmachine.rb:1033:in`spawn_threadpool'
    /usr/lib64/ruby/gems/1.8/gems/eventmachine-1.0.0/lib/eventmachine.rb:1023:in `defer'
    /usr/lib64/ruby/gems/1.8/gems/thin-1.5.0/lib/thin/connection.rb:51:in`process'
    /usr/lib64/ruby/gems/1.8/gems/thin-1.5.0/lib/thin/connection.rb:39:in `receive_data'
    /usr/lib64/ruby/gems/1.8/gems/eventmachine-1.0.0/lib/eventmachine.rb:187:in`run_machine'
    /usr/lib64/ruby/gems/1.8/gems/eventmachine-1.0.0/lib/eventmachine.rb:187:in `run'
    /usr/lib64/ruby/gems/1.8/gems/thin-1.5.0/lib/thin/backends/base.rb:63:in`start'
    /usr/lib64/ruby/gems/1.8/gems/thin-1.5.0/lib/thin/server.rb:159:in `start'
    /usr/lib64/ruby/gems/1.8/gems/rack-1.4.1/lib/rack/handler/thin.rb:13:in`run'
    /usr/lib64/ruby/gems/1.8/gems/sinatra-1.3.3/lib/sinatra/base.rb:1350:in `run!'
    /usr/lib64/ruby/gems/1.8/gems/puppet-rundeck-0.0.7/bin/puppet-rundeck:63
    /usr/bin/puppet-rundeck:19:in`load'
    /usr/bin/puppet-rundeck:19

And my /etc/puppet/puppet.conf (just in case) : 

$ cat /etc/puppet/puppet.conf 
[main]
  logdir = /var/log/puppet
  rundir = /var/run/puppet
  ssldir = $vardir/ssl
  pluginsync = true

[production]
  modulepath = $confdir/environments/production/modules
  manifest = $confdir/environments/production/manifests/site.pp

[development]
  modulepath = $confdir/environments/development/modules
  manifest = $confdir/environments/development/manifests/site.pp

[testing]
  modulepath = $confdir/environments/testing/modules
  manifest = $confdir/environments/testing/manifests/site.pp

[agent]
  server = puppet.xxxxxxxxxxxxxx.com
  runinterval = 14400 
  classfile = $vardir/classes.txt
  localconfig = $vardir/localconfig
  report = true

[master]
  templatedir=/etc/puppet/node_templates
  modulepath=/etc/puppet/modules
  reports = puppet_dashboard,store
  reportdir = /var/lib/puppet/reports
  reporturl = http://puppet.xxxxxxxxxx:3000/reports
  storeconfigs = true
  dbadapter = mysql
  dbuser = puppet
  dbpassword = xxxxxxx
  dbserver = xxxxxxxxxxxxxx

**Comment by adedommelin-zz** [comment]
Fixed a corrupted yaml file in /var/lib/puppet/yaml/node/ and works fine now. Sorry for the incovenience.
